-- Example script to drop all tables used by this library/scripts. Useful for developer
-- testing. Copy as sql\drop_tables.sql and uncomment the last two lines. Do not deploy
-- uncommented version on production. See README.md for more information.
-- DROP TABLE IF EXISTS files, project, language, country, bannerimpressions,
--   landingpageimpression_raw, donatewiki_unique;